name: "OpenSauced Pizza Action"
description: "GitHub Action to run OpenSauced's Pizza CLI's various commands"
branding:
  icon: "image"
  color: "orange"
inputs:
  pizza-args:
    description: "OpenSauced Pizza CLI command to run"
    default: "generate codeowners ./"
    required: true
  commit-and-push:
    description: "Commit and push changes"
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22.5"

    - name: Install pizza CLI
      run: |
        go install github.com/open-sauced/pizza-cli@beta
      shell: bash

    - name: Check pizza CLI version
      run: pizza-cli version
      shell: bash

    - name: Run pizza CLI command
      run: |
        pwd
        ls -la
        pizza-cli ${{ inputs.pizza-args }}
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      if: ${{ inputs.commit-and-push == 'true' }}
      run: ./commit-and-push.sh
      shell: bash
      working-directory: ${{ github.workspace }}
